spring.application.name=meru-backend
server.port=8080

# --- SEGURIDAD / KEYCLOAK ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/meru-app

# --- SWAGGER / OPENAPI ---
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# --- CONFIGURACIÓN DE POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/meru_app
spring.datasource.username=postgres
spring.datasource.password=Hola123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Usamos 'validate' basándonos en tu skill: Hibernate validará que las entidades
# de Java coincidan con tus tablas, pero NO modificará tu base de datos.
spring.jpa.hibernate.ddl-auto=validate